### ISSUE TITLE
Video not playing correctly

### ISSUE THREAD

**Issue by rajganeshp** [StaticMania/portio-hugo#10]
The embeded video in the main home page is not playing correctly. You can check at https://www.connectthoughts.com/

**Comment by AaronNBrock** [comment]
Nice catch!  I accidentally removed the `magnific-popup` when doing some refactoring, I created a PR to fix it.

**Comment by rajganeshp** [comment]
THanks for the  quick response. How do I get the updates? can you send the
git command if you don't mind. thanks.

**Comment by AaronNBrock** [comment]
That's going to depend a little bit on your setup.  The easiest solution would be to wait till @rajganeshp accepts the PR then update your theme submodule.

However, if you really want the fix now, you'd have to do something along the lines of:
https://stackoverflow.com/a/914090/7607701

And change the remote to `https://github.com/AaronNBrock/portio-hugo` and the branch to `fix-issue-10`
