### ISSUE TITLE
How to store secret in Hugo Deployment?

### ISSUE THREAD

**Issue by imjuanleonard** [StaticMania/portio-hugo#18]
Hey, I know it might not be the right place to ask.
But seems you guys are expert in making this awesome template, do you have any suggestion where should I put the API key?

I don't think the config.toml is secure enough?

**Comment by Error6251** [comment]
As far as I can tell you can save your API key locally and use .gitignore to hide it from github repo... OR you can read this... https://discourse.gohugo.io/t/where-should-i-store-api-keys/903

**Comment by imjuanleonard** [comment]
Thanks really helpful

**Comment by imjuanleonard** [comment]
Ah looks like even the guy on discourse didn't find anything on making the config.toml read environment haha. I guess I will post this on hugo issue, thank you
