### ISSUE TITLE
Adding slider/slick dots under the service section 

### ISSUE THREAD

**Issue by lalde** [StaticMania/portio-hugo#24]
Hi, 

First of all thank you for the theme, it's been really easy to work with and customize! 

I just have one small issue: I have 7 items under the service section, but only 5 show up and it is not very intuitive that you have to click/drag to let the last 2 appear. Is there a way to add some sliding/slick dots under the section, to make it obvious that not all the items are shown? 

Thank you!

**Comment by Error6251** [comment]
The main design doesn't have any dots. That's why we didn't add any dots on the services section. If you want to add dot... go to "assets/js/script.js" on line 90 change "dots: true"...
