### ISSUE TITLE
Netlify error no access rights to theme

### ISSUE THREAD

**Issue by santiyounger** [StaticMania/portio-hugo#26]
Hey, thanks for the awesome theme, 

I'm having trouble deplying to Netlify.

I have a similar problem to that of issue https://github.com/StaticMania/portio-hugo/issues/7 and https://github.com/StaticMania/portio-hugo/issues/17
However after trying those solutions it still doesn't work for me.

I have a nice working first version of a website, but I'm having issues deploying it with netlify.

## Working locally

my website works perfectly when using `hugo sever` with local host.

## Setup

I added it as a submodule and made sure to follow the instructions perfecty,

I set everything up correctly with netlify, following the process I've used for other hugo sites.

but I get this error in netlify:

```
Error checking out submodules: Submodule 'themes/portio'
Permission denied (publickey)
fatal: Could not read from remote repository
Please make sure you have the correct access rights

```

<details>
<summary>Extended version of netlify error</summary>
9:16:19 AM: Preparing Git Reference refs/heads/master
9:16:21 AM: Error checking out submodules: Submodule 'themes/portio' (git@github.com:StaticMania/portio-hugo.git) registered for path 'themes/portio'
Cloning into '/opt/build/repo/themes/portio'...
Warning: Permanently added 'github.com' (RSA) to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:StaticMania/portio-hugo.git' into submodule path '/opt/build/repo/themes/portio' failed
Failed to clone 'themes/portio'. Retry scheduled
Cloning into '/opt/build/repo/themes/portio'...
Permission denied (publickey).

fatal: Could not read from remote repository.
</details>

I've worked with other hugo themes and I've never had this issue before.

Are there any extra steps I need to take to stop having the error message `Permission denied (publickey).` that netlify produces?

## Attempts to fix
Like mentioned at the beginning I did try the solutions mentioned  https://github.com/StaticMania/portio-hugo/issues/7 and https://github.com/StaticMania/portio-hugo/issues/17

I change `baseURL`   to use `https` instead of `http` and I also installed hugo extended  through snap. 

Previously I had hugo installed from the Arch Linux AUR, but I uninstalled that one to use extended version with snap. which seems to work without any issues with `hugo server`

## Specs
Linux Manjaro with Awesome WM

I apprecaite any help, have been stuck with this for a couple of days.
Thank you so much once again for your great work!
- Santi

**Comment by Error6251** [comment]
Instead of using sub module please try to fork the project, and then install the theme from your repo. I'm not sure but, Netlify may have some issue for giving permission to other repo.

**Comment by santiyounger** [comment]
Thank you, I will try that out to see if it work! thanks for the help

**Comment by uncledent** [comment]
You can also add submodule via https instead of ssh, so it will also work

**Comment by santiyounger** [comment]
> You can also add submodule via https instead of ssh, so it will also work

Hey, thanks for the help, I've added the submodule just as instructed in the README

`git submodule add git@github.com:StaticMania/portio-hugo.git themes/portio` is that being done through ssh? If so how do I make it work via https

**Comment by mys921** [comment]
I wonder if Netlify already solved this problem, and we just need to document it in Portio as part of the "Getting Started" are:
https://docs.netlify.com/configure-builds/repo-permissions-linking/#deploy-keys
