### ISSUE TITLE
Multilingual Web Site

### ISSUE THREAD

**Issue by sevocrear** [StaticMania/portio-hugo#28]
Hi! Could you, please, provide some info how to do your wonderful web site template multilingual?  I tried to add 2nd language following some guides, but it didn't work at all... I would like to have all partials and contents translated

**Comment by sevocrear** [comment]
Thx. I've solved the problem on my own. Also, I noticed that site map worked strange. It didn't show, for example, last article if I chose. But I change some lines in html files and right now every thing works like a charm.

**Comment by jacobfederer** [comment]
Hi @sevocrear, I'm currently trying to achieve to the same. Could you maybe share your solution? That would really help out!

**Comment by sevocrear** [comment]
Yeah, sure! I've put my site files into a private
 sevocrear_bio_site-main.zip
<https://drive.google.com/file/d/1SWgaEU5K9zp6QFi8qUfFmA2KQ2fqZbdh/view?usp=drive_web>
repository so I'll share all files of it in zip. I think that my changings
are clear here that allowed me to solve multilingual problems with this
design=-)  Sorry, for now I don't have plenty of time to put a detailed
comment into the github issues. Anyway, I hope, it will be helpful.

>

**Comment by sevocrear** [comment]
> Hi @sevocrear, I'm currently trying to achieve to the same. Could you maybe share your solution? That would really help out!

If you have any questions, just ask=-) I would be glad to help

**Comment by jacobfederer** [comment]
Perfect, thanks! I'll try to figure it out in the next couple of days.

**Comment by Yannovitch** [comment]
Hi, would it be possible to share the changes you did ? I'm interested too in achieving a multilingual portio template. It would be much appreciated ^^ Thank you ! Yann

**Comment by sevocrear** [comment]
> Hi, would it be possible to share the changes you did ? I'm interested too in achieving a multilingual portio template. It would be much appreciated ^^ Thank you ! Yann

Good afternoon, I've opened the repo. You can find it here: https://github.com/sevocrear/sevocrear_bio_site.git

**Comment by rokib-rajon** [comment]
@sevocrear Hi, How do you implement Forestry cms for multilingual blog post ? Can you share the forestry config ?
