### ISSUE TITLE
adding opengraph,twitter_cards and schema is proving to be a hustle. Please help.

### ISSUE THREAD

**Issue by stephenajulu** [StaticMania/portio-hugo#31]
Hi, how are you?
I am having issues adding opengraph, twitter cards and schema tags to my site.
Opengraph defaults to my fallback image("images = " that i had to set up otherwise would have no image)
Twitter card only shows a summary no image.
I tried editing gohugo's versions and adding featureImage and postImage but it fails to build.
I have already set up [author] in the config.
Kindly help me display both post images and the image set for Home.

**Comment by Error6251** [comment]
I need to see the code. Can I have the repo, where you're working right now...

**Comment by stephenajulu** [comment]
https://github.com/stephenajulu/stephenajulu1.2
It would be great, if you can help me

**Comment by kausarpial** [comment]
You've range through `authors` but the author ain't iterable on config

```
{{ with .Site.Author -}}
<meta name="twitter:creator" content="@{{ .twitter }}"/>
{{ end -}}
```
try this out without range. it'll work

Thanks

**Comment by stephenajulu** [comment]
Thank you
