### ISSUE TITLE
JS issue

### ISSUE THREAD

**Issue by hpdipto** [StaticMania/portio-hugo#33]
I'm running the theme locally and facing this issue:

- When scrolling down, the navbar color is not change. It remains transparent.
- The create service lists are also not displayed vertically but it displays horizontally.

Please see the image below:
![portio_issue](https://user-images.githubusercontent.com/26406114/108973611-bf409580-76ae-11eb-9b08-3af98571cc6d.png)

**Comment by hpdipto** [comment]
I think the main problem that I'm facing is for some reason `/assets/js/script.js` not loading.

**Comment by hpdipto** [comment]
I noticed the [issue#1](https://github.com/StaticMania/portio-hugo/issues/1), and it solved my issue temporarily. But it supposed to resolve for other versions too.

**Comment by Error6251** [comment]
Please give us your repository link, and what version your using?

**Comment by hpdipto** [comment]
I didn't create any repository yet. I'm using latest version 0.81.0.

**Comment by hpdipto** [comment]
any update from team? let me tell you some more findings. it mostly failed to load the minified js. when `| minify` section is removed, it works nicely.

**Comment by ronopixels** [comment]
Hi @hpdipto 
We always prefer users to use the latest stable Hugo version. Let us go through with the version you've mentioned. You can also send us a PR with solve, we'll review that.

Thanks

**Comment by hpdipto** [comment]
The js minification error was caused by the leading zeros of a number. I create a  [pull request](https://github.com/StaticMania/portio-hugo/pull/34), please check it.
