### ISSUE TITLE
Help me to Implement search option, tags and category page

### ISSUE THREAD

**Issue by rokib-rajon** [StaticMania/portio-hugo#40]
I have tried several methods found on the internet to implement a search option and add a page for tags and categories, but nothing works with this theme. As a non programmer, its hard for me to do this. Can you give me a good documentation which will work with this amazing theme? 

Thanks in advance !

**Comment by Error6251** [comment]
For tags and category try [Taxonomies](https://gohugo.io/content-management/taxonomies/) from hugo docs.

**Comment by rokib-rajon** [comment]
@Error6251 Tried the methods you mentioned, but no results. After few hours of trying  I found a way to do it. Copied the code from the layout of blog list page, I pasted it on default list page. Then I change the range from {{ range .Paginator.Pages }} to {{ range $index, $page := .Paginator.Pages }}. It solved the problem partially. It can not render page to show all taxonomies at once  like /category or /tags, but able to render page for single taxonomy like /category/lorem or /tags/lorem. How can I solve this issue ?

**Comment by Error6251** [comment]
From the Doc. You need to declare taxonomies on your config.toml file [Read here](https://gohugo.io/content-management/taxonomies/#default-taxonomies).
`[taxonomies]
  tag = "tags"`

On your content's markdown file add tag
`tags: "news"`

Then, You need to create a folder on your "layout" folder and create a taxonomy.html file.
`layouts/tags/taxonomy.html`

[For more info.](https://youtu.be/pCPCQgqC8RA)

[For Example](https://github.com/StaticMania/blogge-hugo-theme.git)
