### ISSUE TITLE
different buttons between desktop and mobile version

### ISSUE THREAD

**Issue by AntoineSoetewey** [StaticMania/portio-hugo#42]
Hello,

Here are the two buttons on desktop:

![Screenshot 2021-08-18 at 15 31 19](https://user-images.githubusercontent.com/17910063/129907137-e38d3b74-07ca-401a-8128-91c3f1754881.png)

But then on mobile, the one in the hero section is different:

![IMG_E5DFC91687C2-1](https://user-images.githubusercontent.com/17910063/129907359-e8ee0f3f-7b0a-4dca-ad77-5939eb7436dd.jpeg)

is it possible to change the button in the hero section to match the one in the navbar?

I tried to edit it in the code, without success.

Thanks in advance for your help!

(if you need, here is my website using your template: [easystat.be](https://easystat.be/))

Regards,
Antoine

**Comment by AntoineSoetewey** [comment]
thanks !

should it be placed anywhere in this file: https://github.com/StaticMania/portio-hugo/blob/master/layouts/partials/hero.html ?

**Comment by Error6251** [comment]
nah...
add a new line [here](https://github.com/StaticMania/portio-hugo/blob/efbea690d277f6c15071ca76e8f5e0ac521c761a/assets/scss/_buttons.scss#L16) then add this three line of code...
```
-webkit-appearance: none;
-moz-appearance: none;
appearance: none;
```
I hope it will work if not, Pls feel free inform here.

**Comment by AntoineSoetewey** [comment]
it worked, thanks a lot !
