### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by anthonyjdella** [StaticMania/portio-hugo#44]
Hi, I'm having the issue of setting this up with Github Pages and was looking for assistance.

I have created a new Hugo site and added Portio as a submodule, then copied the files from the exampleSite to my root. The site will build and run locally.

Initially I had an issue with the submodule that linked to this: [link.](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-submodule) To fix this, I changed the submodule from ssh to https.

But now, I'm getting a new error on my repo's Pages settings:

` Your site is having problems building: There was a YAML syntax error on line 2 column 1 in <unknown>: did not find expected key while parsing a block mapping. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-yaml-in-data-file.`

My GitHub Pages settings are building from:
branch -> main
folder -> / (root)

**Comment by anthonyjdella** [comment]
I got it to work now: [visit the site here](https://anthonyjdella.github.io/)

However, the theme is not being applied. Am I doing something wrong? I used this theme as a submodule, not by cloning, so not sure what the issue is.

**Comment by anthonyjdella** [comment]
Fixed issue by changing baseUrl in config.toml. It needs to point to the correct url so that it can pick up the generated scss files. In my case I had to change baseUrl to `baseURL = "https://[username].github.io/"`

**Comment by tanimmahmud** [comment]
Hi @anthonyjdella , how did you fix the original problem? is it possible to see your github action scripts? Thanks

**Comment by anthonyjdella** [comment]
@tanimmahmud Sorry Tanim, I can't remember how I fixed the initial issue. But here is a link to my [GitHub action script](https://github.com/anthonyjdella/personal-website/blob/master/.github/workflows/firebase-hosting-merge.yml). Hope that helps!
