### ISSUE TITLE
Pagnation Issues on mobile

### ISSUE THREAD

**Issue by stephenajulu** [StaticMania/portio-hugo#45]
Hi, I'm experiencing issues with pagnation. The page numbers go out of the screen on mobile.

![Screenshot_2021-11-20-20-05-36-215_com microsoft emmx](https://user-images.githubusercontent.com/42298053/142734985-484746ee-5649-4d6f-bbae-8aca95f670e6.jpg)

Is there a fix?

**Comment by Error6251** [comment]
I'm not sure but you can try

**Comment by Error6251** [comment]
I'm not sure but you can try to limit how many page number you want to show...

on portio-hugo > layouts > partials > pagination.html 
https://github.com/StaticMania/portio-hugo/blob/efbea690d277f6c15071ca76e8f5e0ac521c761a/layouts/partials/pagination.html#L5
```
{{ $pageLimit := 3 }}
{{ range $index, $element := $pag.Pagers }}
  {{ if eq . $pag }}
    <li class="page-item active">
      <a class="page-link" href="{{ $element.URL }}">{{ $element.PageNumber }}</a>
    </li>
  {{ else }}
    {{ if le $index $pageLimit }}
    <li class="page-item">
      <a class="page-link" href="{{ $element.URL }}">{{ $element.PageNumber }}</a>
    </li>
  {{ end }}
{{ end }}
```
You can try it but, I can't ensure you that, it will work!

**Comment by stephenajulu** [comment]
Hi, thank you for the response.
I tried it but the site couldn't build.
Could you kindly share your full solution(code)?
Could be something I did.

**Comment by stephenajulu** [comment]
I have more than 90 posts and displaying 30 at once isn't a good solution.

**Comment by Md-Saad** [comment]
** you can try the following steps.

1. replace codes on portio-hugo > layouts > partials > pagination.html by the following codes

{{ $paginator := $.Paginator }}

{{ $adjacent_links := 2 }}

{{ $max_links := (add (mul $adjacent_links 2) 1) }}

{{ $lower_limit := (add $adjacent_links 1) }}

{{ $upper_limit := (sub $paginator.TotalPages $adjacent_links) }}

{{ if gt $paginator.TotalPages 1 }}

<nav aria-label="Page navigation" class="w-100">
  <ul class="pagination justify-content-center pagination-lg">
    
    {{ if ne $paginator.PageNumber 1 }}
      <li class="page-item">
        <a class="page-link" href="{{ $paginator.First.URL }}">
	    First
        </a>
      </li>
    {{ end }}
    
    {{ if $paginator.HasPrev }}
      <li class="page-item">
        <a class="page-link" href="{{ $paginator.Prev.URL }}" rel="next">
          ←
        </a>
      </li>
    {{ end }}
    
    {{ range $paginator.Pagers }}
      {{ $.Scratch.Set "page_number_flag" false }} 
      
      {{ if gt $paginator.TotalPages $max_links }}
        
        
        {{ if le $paginator.PageNumber $lower_limit }}
          
          {{ if le .PageNumber $max_links }}
            {{ $.Scratch.Set "page_number_flag" true }}
          {{ end }}
        
        
        {{ else if ge $paginator.PageNumber $upper_limit }}
          
          {{ if gt .PageNumber (sub $paginator.TotalPages $max_links) }}
            {{ $.Scratch.Set "page_number_flag" true }}
          {{ end }}
        
        {{ else }}
          {{ if and ( ge .PageNumber (sub $paginator.PageNumber $adjacent_links) ) ( le .PageNumber (add $paginator.PageNumber $adjacent_links) ) }}
            {{ $.Scratch.Set "page_number_flag" true }}
          {{ end }}
        {{ end }}
      
      {{ else }}
        {{ $.Scratch.Set "page_number_flag" true }}
      {{ end }}
      
      {{ if eq ($.Scratch.Get "page_number_flag") true }}
        <li class="page-item{{ if eq . $paginator }} active{{ end }}">
          <a class="page-link" href="{{ .URL }}" >
            {{ .PageNumber }}
          </a>
        </li>
      {{ end }}
    {{ end }}
   
    {{ if $paginator.HasNext }}
    <li class="page-item">
      <a class="page-link" href="{{ $paginator.Next.URL }}" >
        →
      </a>
    </li>
    {{ end }}
    
    {{ if ne $paginator.PageNumber $paginator.TotalPages }}
    <li class="page-item">
      <a class="page-link" href="{{ $paginator.Last.URL }}">
	Last
      </a>
    </li>
    {{ end }}
  </ul>
  
</nav>
{{ end }}

2. Now add this following sccs codes to make it mobile friendly on assets/scss/components/_blog.scss
@include mobile{
	.pagination{
		.page-item{
			.page-link{
				padding: 0.35rem 0.7rem;
				font-size: 1rem;
			}
		}
	}
