### ISSUE TITLE
Is the theme still maintained?

### ISSUE THREAD

**Issue by AntoineSoetewey** [StaticMania/portio-hugo#47]
Hello,

Thanks again for this great theme!

I see that the last commit dates back from 6 months ago and there are several pull requests and issues still open.

Does this mean that this repo/theme is not maintained anymore?

I’m always a bit scared to use a theme which is not actively maintained anymore.

Regards,
Antoine

**Comment by Error6251** [comment]
Yes are still maintaining this theme. We will re-check all the repo. It may take some time!

**Comment by AntoineSoetewey** [comment]
> Yes are still maintaining this theme. We will re-check all the repo. It may take some time!

Thanks !
