### ISSUE TITLE
How to insert image from directory?

### ISSUE THREAD

**Issue by dnth** [StaticMania/portio-hugo#49]
How do I insert image from the local directory? I place my images in the static folder. However, I could not have it display on my blog post.

This is what I wrote in my `first-blog-post.md`
`![Example image](/static/images/blog/screenshot.png)`

**Comment by Error6251** [comment]
```![Example image](/images/blog/screenshot.png)```
try without motioning the static part and make sure your image is on
`project-root > static > images > blog > screenshot.png`

**Comment by dnth** [comment]
Great! Thank you so much!

**Comment by Error6251** [comment]
https://www.w3schools.com/tags/att_img_width.asp

**Comment by dnth** [comment]
I put this into my markdown file and the image does not seem to render on the page. Did I missed anything?


`<img src="/images/blog/screenshot.png" alt="Girl in a jacket" width="500" height="600">`

**Comment by Error6251** [comment]
You can't use HTML on a markdown file. I think, for that reason you need some photo editing tool to change that image size to 500x600

**Comment by dnth** [comment]
For future refence adding this shortcode to my markdown file works to control the image size

`{{< figure src="/images/blog/screenshot.png" alt="Screenshot of the Onion homepage" width=750 >}}`
