### ISSUE TITLE
Add "Skills" to site header

### ISSUE THREAD

**Issue by dnth** [StaticMania/portio-hugo#50]
![Screenshot from 2022-01-13 18-04-03](https://user-images.githubusercontent.com/6821286/149309208-e6389f34-42ba-4e08-a9f1-7b4fdef5254b.png)

How do we properly add "Skills" on the webpage header? I added them in the `config.toml` file but could not link it to the Skills section.

**Comment by Error6251** [comment]
first you need to create a page for skill if you want a skill page, or if you just want a skill section on home page create a section add the section on the page. on config.toml add something like this:
```
[[menu.main]]
name = "Skill"
url = "#skill"
weight = 7
```
add an ID on your skill section tag...

I will be happy to help you if you give me the repo link where you are working... 😃

**Comment by dnth** [comment]
Thank you! I have done exactly as you specified there. But when I click on the Skills section it doesnt bring me to the Skills section. 

Here is my repo
https://github.com/dnth/dnth.github.io
