### ISSUE TITLE
Add table of contents for blog posts

### ISSUE THREAD

**Issue by dnth** [StaticMania/portio-hugo#53]
Is there any plan to add Table of Contents for blog post? I will be happy to work on a PR if there is anyone who can provide guidance.

**Comment by raiden076** [comment]
> Is there any plan to add Table of Contents for blog post? I will be happy to work on a PR if there is anyone who can provide guidance.

I am planning, to finally build my website and blog, and if the blog has toc, then I can't even think of any other choice..!!!

**Comment by dnth** [comment]
I have added toc support in this PR https://github.com/StaticMania/portio-hugo/pull/54
