### ISSUE TITLE
How to change buttons in footer and header?

### ISSUE THREAD

**Issue by DukeFR** [StaticMania/portio-hugo#56]
Hi, I would like to know where can i change the text in the "Hire Me" button in the header and the "Get in Touch button" in the footer?

Thanks!

**Comment by Error6251** [comment]
https://github.com/StaticMania/portio-hugo/blob/ccae0510631bc00e477fa2438cdcd38022eaf5c9/layouts/partials/navbar.html#L23
https://github.com/StaticMania/portio-hugo/blob/ccae0510631bc00e477fa2438cdcd38022eaf5c9/layouts/partials/footer.html#L30

**Comment by DukeFR** [comment]
Thanks for the anwser, that's perfect, have a great day!
