### ISSUE TITLE
Is there a way to have tags for blogs?

### ISSUE THREAD

**Issue by rajganeshp** [StaticMania/portio-hugo#8]
The previous Hugo templates had TAGs. So it show the tags in the bottom of the blog. And if I click on any tag, it brings all relevant blogs with same tags. Is there a way to get same functionality? Thanks.

**Comment by AaronNBrock** [comment]
As far as I know;  No, there are not.  Feel free to add the functionality though & create a PR!  (or I'll take a swing at it once I finish my bootstrap refactors).

**Comment by rajganeshp** [comment]
I don't think i will know how to do that :)

**Comment by kausarpial** [comment]
Currently, we don't have the support of tags in blog
@rajganeshp
